theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
url: https://kumanidev.github.io
baseurl: /jekyllproject/
title: Kumani's Life
description: Learn more about me
author: Kumani Riley
