theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
baseurl: https://kumanidev.github.io
url: /jekyllproject/
title: Kumani's Life
description: Learn more about me
author: Kumani Riley
