list:
- image:""
  image-alt: Image 1
  title: Project 1
  list-content: This is what the first project is about ...


- image:""
  image-alt: Image 2
  title: Project 2
  list-content: This is what the second project is about ...

- image:""
  image-alt: Image 3
  title: Project 3
  list-content: This is what the third project is about ...